### PR TITLE
Make TikTok username optional based on scopes set

### LINKED ISSUE #1198: 500 Server Error with TikTok
Got a weird one here.  I've set up the TikTok provider and have gone through the application process with TikTok.  I've requested and been approved for the `user.info.basic` and `user.info.profile` scopes.

The weirdness happens when I actually try to login with a TikTok account.  I get sent to the correct oAuth approval screen and I correctly approve it, but when I get redirected to my app, my app throws a 500 Server Error.

The redirect URI I get sent back to is `https://MYAPP/auth/tiktok/callback?code=2-vF-hhkIvD34ZPoyBLAHBLAHBLAHBLAHBLAHBLAHBLAHBLAHBLAHBLAH81jiR34sCen7wwmI-995ebt9N22PbSZ2AMw5BLAHBLAHBLAHBLAHBLAHBLAHBLAHBLAHbkwvitP-IsmA_vELfgqBLAHBLAHtMfS89IETiVvcBLAHBLAHBLAHBLAHBLAHBLAHseH6PgqnJXjP8MdSyGN0PsCcw-stSV26%2A1%214608.va&scopes=user.info.basic&state=zYVWqwVR5GJBLAHBLAHBLAHBLAH`

And it shows that the `scopes` value is `user.info.basic`, a scope I've been approved for, but if I check `storage/logs/laravel.log`, I see this error:

```
[2024-04-23 22:51:33] production.ERROR: Client error: `GET https://open.tiktokapis.com/v2/user/info/?fields=open_id%2Cunion_id%2Cdisplay_name%2Cavatar_large_url%2Cusername` resulted in a `401 Unauthorized` response:
{"error":{"code":"scope_not_authorized","message":"The user did not authorize the scope required for completing this req (truncated...)
 {"exception":"[object] (GuzzleHttp\\Exception\\ClientException(code: 401): Client error: `GET https://open.tiktokapis.com/v2/user/info/?fields=open_id%2Cunion_id%2Cdisplay_name%2Cavatar_large_url%2Cusername` resulted in a `401 Unauthorized` response:
{\"error\":{\"code\":\"scope_not_authorized\",\"message\":\"The user did not authorize the scope required for completing this req (truncated...)
 at /home/[MYAPP]/vendor/guzzlehttp/guzzle/src/Exception/RequestException.php:113)
```

Does anyone have any insight as to why this might be happening?

### PR DESCRIPTION
**Pull request by Skullbock**
In v2, `username` can be requested only if `user.info.profile` scope is set.
Instead of forcing the scope, since it's not even in the default list of scopes set in the provider, we could just add the username field if the scope is present.

Closes #1198

### CODE REVIEW

**Review by lucasmichot — APPROVED** [review]

File: src/TikTok/Provider.php [hunk 1]
```diff
@@ -98,12 +98,23 @@ protected function getTokenFields($code)
...
     protected function getUserByToken($token)
     {
+        $fields = [
+            'open_id', 
+            'union_id',
+            'display_name',
+            'avatar_large_url',
+        ];
+
+        if (in_array('user.info.profile', $fields)) {
```
Comment (atymic) [inline src/TikTok/Provider.php:108]: Hmm should this not be checking scopes, not `$fields` ?

**Review by atymic — CHANGES_REQUESTED** [review]
See comment

**Comment by liamseys** [comment]
I got approved and added this scope, but I still can't see the username.

**Comment by liamseys** [comment]
@atymic I debugged this: the username field isn't being passed to the fields list when the scope was added. Was this tested before merging?

**Comment by atymic** [comment]
@liamseys can you share the scopes you're using in laravel?

**Comment by liamseys** [comment]
@atymic

```
return Socialite::driver('tiktok')
            ->scopes(['user.info.basic', 'user.info.profile'])
            ->redirect();
```

**Comment by liamseys** [comment]
Scherm­afbeelding 2024-06-12 om 16 13 49

**Comment by liamseys** [comment]
```
array:1 [▼ // vendor/socialiteproviders/tiktok/Provider.php:107
  0 => "user.info.basic"
]
```

When I print ```$this->scopes``` in the Provider.php file, I only see user.info.basic, even though I set more in the scopes method.

**Comment by atymic** [comment]
It should merge them correctly
Screen Shot 2024-06-13 at 08 38 25

Can you show your whole controller? Do you set the scopes also when you call `->user();`
